apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

    # Alertmanager configuration
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          # - alertmanager:9093

    # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.

    scrape_configs:

      - job_name: 'prometheus'

        # metrics_path defaults to '/metrics'
        # scheme defaults to 'http'.

        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'node_exporter_metrics'
        scrape_interval: 15s
        scrape_timeout: 15s
        static_configs:
        - targets: ['3.83.106.103:9100']
      - job_name: 'cadvisor'
        static_configs:
        - targets: ['3.83.106.103:8080']

      - job_name: 'kubernetes-nodes'

        scheme: https

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
        - role: node

        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics
          
      - job_name: 'kubernetes-pods'

        kubernetes_sd_configs:
        - role: pod

        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
      # Scrape config for Kubelet cAdvisor.
      - job_name: 'kubernetes-cadvisor'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: node
      
        relabel_configs:
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      
        metric_relabel_configs:
        # Only keep systemd important services like docker|containerd|kubelet and kubepods,
        # We also want machine_cpu_cores that don't have id, so we need to add the name of the metric in order to be matched
        # The string will concat id with name and the separator is a ;
        # `/;container_cpu_usage_seconds_total` OK
        # `/system.slice;container_cpu_usage_seconds_total` OK
        # `/system.slice/minion.service;container_cpu_usage_seconds_total` NOK, Useless
        # `/kubepods/besteffort/e2514ad43202;container_cpu_usage_seconds_total` Best Effort POD OK
        # `;machine_cpu_cores` OK, there is no id on these metrics, but we want to keep them also
        - source_labels: [id,__name__]
          regex: "^((/(system.slice(/(docker|containerd|kubelet).service)?|(kubepods|docker).*)?);.*|;(machine_cpu_cores|machine_memory_bytes))$"
          action: keep
        # Remove Useless parents keys like `/kubepods/burstable` or `/docker`
        - source_labels: [id]
          regex: "(/kubepods/burstable|/kubepods/besteffort|/kubepods|/docker)"
          action: drop
          # cAdvisor give metrics per container and sometimes it sum up per pod
          # As we already have the child, we will sum up ourselves, so we drop metrics for the POD and keep containers metrics
          # Metrics for the POD don't have container_name, so we drop if we have just the pod_name
        - source_labels: [container_name,pod_name]
          regex: ";(.+)"
          action: drop
      
      
